### PR TITLE
fixed initialization order behind proxy

### PR DESCRIPTION
**Pull request by inidona**
- [ x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ x] Ensure that the pull request title represents the desired changelog entry
- [x ] Please describe what you did
- [x ] Link to relevant issues in GitHub or Jira
- [ x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

I fixed the order because the withConfig Method creates internally a new config so that the proxy settings are lost.
I tested it with our Jenkins instance behind the proxy.

Error comes up with https://github.com/jenkinsci/urltrigger-plugin/issues/48

### CODE REVIEW

**Comment by TonyNoble** [comment]
@inidona - thanks for the fix.  One minor point - I realise the code was already there, but is hard-coding the scheme to 'http' a good idea?  Is there the possibility it might be https?

**Comment by inidona** [comment]
@TonyNoble  i never heard about a proxy addressing by https. I jenkins you configure only a host and port and no protokoll.

**Comment by TonyNoble** [comment]
@inidona - no problem, thanks for the clarification.  I'll get this merged and released over the weekend.

**Comment by basil** [comment]
Sorry for introducing this regression. HTTP proxy code is always tricky to test. Thank you for proposing a PR to fix it.

**Pull request merged**
