### PR TITLE
JENKINS-64081 Fix plugin on 2.264

### PR DESCRIPTION
**Pull request by timja**
https://issues.jenkins-ci.org/browse/JENKINS-64081

cc @TonyNoble @oleg-nenashev

### CODE REVIEW

**Comment by TonyNoble** [comment]
Hi @timja ,

Thanks very much for this - I'll take a look over the weekend and get this merged.

**Review by oleg-nenashev — APPROVED** [review]
The fix itself is pretty straightforward. Looks good to me

**Comment by TonyNoble** [comment]
Merged.  Will release this evening, if possible

**Comment by aptalca** [comment]
Just wondering if a new release will be cut. The current release seems to break all job configuration pages.

Thanks

**Comment by TonyNoble** [comment]
Release 0.48 went out yesterday - should be available already.

**Comment by oleg-nenashev** [comment]
Thanks a lot @timja and @TonyNoble !

**Pull request merged**
