### PR TITLE
Add Jenkinsfile to run the build

### PR DESCRIPTION
**Pull request by ColMelvin**

### CODE REVIEW

**Comment by ColMelvin** [comment]
@TonyNoble @gboissinot

I have plans to make further changes soon (to support pipeline) and would like to have CI ready for validation.  Would you review and merge this change?

If there are any actions I must take (e.g. in [JIRA](https://issues.jenkins-ci.org)), please let me know.

**Comment by TonyNoble** [comment]
@ColMelvin 
Done - let me know what your thoughts are regarding pipeline support - I've been looking in a similar direction, but wouldnt want to duplicate effort...

**Comment by ColMelvin** [comment]
I was thinking of re-submitting PR #15 (or something similar), after xtrigger-lib publishes a new build with the following changes (maybe 0.34?):

- https://github.com/jenkinsci/xtrigger-lib/pull/12
- https://github.com/jenkinsci/xtrigger-lib/pull/13
- https://github.com/jenkinsci/xtrigger-lib/pull/14
- https://github.com/jenkinsci/xtrigger-lib/pull/15

**Comment by ColMelvin** [comment]
@TonyNoble Just a follow-up: the above pull requests were merged into xtrigger-lib.  Once a build is created (and published), it should be possible to update URLTrigger to support pipeline.

How would one get a build published?  Can I create a JIRA case for that?

**Comment by TonyNoble** [comment]
Apologies for the zombie thread resurrection.  Life got in the way of the
work required for this, unfortunately.  That said, I think the bulk of the
issues in the plugin itself are now resolved, it's simply the xtrigger-lib
dependency that's now holding things back.

It looks like there's still bee no movement on a release of xtrigger-lib
though - @oleg-nenashev - is it possible to get that done?  Happy to do it
myself given the correct permissions (and perhaps it wouldn't hurt to have
access, given how closely coupled the two are)

Cheers,

Tony

**Comment by oleg-nenashev** [comment]
Hi @TonyNoble . TBH I forgot the context a bit. IIRC there was a plan to take over the XTrigger Lib ownership. But I am not sure it was done

**Comment by TonyNoble** [comment]
Hi  @oleg-nenashev,

Thanks for the response and apologies - I've just emailed the main dev list
as well, as I wasn't sure this was the correct avenue.  As mentioned in
that email - if I can assist in any way, please let me know.  I'm just not
sure what process is applicable for libs rather than plugins :0)

Tony

**Comment by oleg-nenashev** [comment]
Let's continue the discussion in https://groups.google.com/forum/#!searchin/jenkinsci-dev/XTrigger%7Csort:date/jenkinsci-dev/Ue9hmTRhqS4/Q_IH-2heDAAJ

**Comment by TonyNoble** [comment]
@colmelvin

Hiya, not sure if you're still actively interested in this, but there is
finally progress.

XTrigger changes have been released as 0.34.  Additionally, the URLTrigger
plugin has a pipeline-dev branch that uses 0.34-SNAPSHOT of XTrigger-Lib
(shortly to be updated to 0.34) and should be pipline compatible, as far as
my testing so far is going.  I can send you example pipeline syntax if
you're interested in trying it out?

Tony

**Comment by ColMelvin** [comment]
I can do some quick tests next week after I get back from vacation.

**Comment by TonyNoble** [comment]
Brilliant, thanks.

For reference, I've added a Readme.md to the root of the project with
example pipeline syntax.

Tony

**Comment by ColMelvin** [comment]
I'm having difficulty getting the settings to save with a plain (non-multibranch) pipeline.  I try saving the following configuration:

Screen Shot 2019-08-29 at 16 09 58

but return to find the settings changed to:

Screen Shot 2019-08-29 at 16 09 18

And the behavior in the URLTrigger Log page looks like it's configured how the second image shows.

The polling node and the schedule remain as entered, so that is working.

**Comment by TonyNoble** [comment]
Thanks - obviously spent so much time testing declarative that I missed
that bit.

Out of interest, if you set a json content type using the declarative
format in the pipeline script, does it show up in the job config and
persist?

Tony

**Comment by TonyNoble** [comment]
@ColMelvin - I've uploaded a fix to the branch today, that should resolve
that issue.

Cheers,

Tony

**Comment by TonyNoble** [comment]
@ColMelvin - thanks very much for testing - that should be resolved now.  Was auto-setting the status check when a status value was supplied, forgetting that it was defaulted to 200 through the UI.

Fix uploaded, let me know what you think.  And thanks again for testing, it's much appreciated.

**Comment by ColMelvin** [comment]
Tested with v0.46.  This works as expected.  Thanks for all your work.

**Pull request merged**
